#!/bin/bash
# Quick Start Guide - Razorpay Integration Setup

echo "🚀 ClauseIQ Razorpay Payment Gateway Setup"
echo "=========================================="
echo ""
echo "Step 1: Get Razorpay Credentials"
echo "  1. Visit https://razorpay.com"
echo "  2. Create account and verify email"
echo "  3. Go to Dashboard → Settings → API Keys"
echo "  4. Copy Key ID and Key Secret"
echo ""
echo "Step 2: Configure Environment Variables"
echo "  Create or update .env file with:"
echo ""
echo "  RAZORPAY_KEY_ID=your_key_id"
echo "  RAZORPAY_KEY_SECRET=your_key_secret"
echo "  REACT_APP_RAZORPAY_KEY_ID=your_key_id"
echo ""
echo "Step 3: Restart Development Server"
echo "  npm run dev"
echo ""
echo "Step 4: Test the Integration"
echo "  1. Click on 'PAYG Wallet' or 'Light Membership' plan"
echo "  2. Use test card: 4111 1111 1111 1111"
echo "  3. Use any future expiry and any 3-digit CVV"
echo ""
echo "✅ Setup Complete!"
echo ""
echo "📚 For detailed setup instructions, see RAZORPAY_SETUP.md"
